version: '3.8'

services: 
  node_backend:
    container_name: node_tabnine
    image: node_tabnine:0.0.4
    build: 
      context: .
    ports:
      - "3001:3001"
    environment: 
      - PORT=5000